### PR TITLE
Fix a few typos

### PR DESCRIPTION
**Pull request by pitmonticone**

### CODE REVIEW

**Comment by pitmonticone** [comment]
Hi @storopoli and @torfjelde, 

Thank you very much for making this material open for free. 

Has the workshop been recorded and, if so, will it be publicly available later?

**Comment by torfjelde** [comment]
> Has the workshop been recorded and, if so, will it be publicly available later?

Unfortunately not :confused: The slides I used in my presentation are available here: https://torfjelde.github.io/presentations/2023-01-25-Geilo-Winter-School/, but no recording.

**Comment by torfjelde** [comment]
Btw, I very much appreciate this PR! But I export all the files from the `notes.org` file, and so any changes made to `notes.md` or `notes.ipynb` will be gone when I regenerate from `notes.org`  (which is not unlikey, e.g. if I fix some other typos or something).

**Review by storopoli — APPROVED** [review]
Thanks once again my friend. You are a Bayesian blessing.

**Comment by pitmonticone** [comment]
Thank you guys, keep up your amazing work. 

I'm learning a lot from reading your material and I can't resist giving (even if it's trivial amount) back.

**Pull request merged**
